apiVersion: v1
kind: Pod
metadata:
  name: filesystem-storage-example
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    volumeMounts:
    - mountPath: /storage
      name: comfyui
  volumes:
  - name: comfyui
    persistentVolumeClaim:
      claimName: comfyui